# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserImageUploadRoute: image_upload
            filebrowserImageBrowseRoute: image_browser
            allowedContent: true
            shiftEnterMode: 'CKEDITOR.ENTER_P'