presta_sitemap:
   defaults:
      priority: 1
      changefreq: weekly
      lastmod: now
   timetolive: 3600
   items_by_set: 50000
   generator: presta_sitemap.generator_default
   dumper: presta_sitemap.dumper_default