sonata_admin:
    title: 'drupai Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [sonata.admin]

services:
    sonata.admin.category:
        class: App\Admin\CategoryAdmin
        arguments: [~, App\Entity\Category, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: 分类管理 }

    sonata.admin.article:
        class: App\Admin\ArticleAdmin
        arguments: [~, App\Entity\Article, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: '文章内容' }

    sonata.admin.visit:
        class: App\Admin\VisitLogAdmin
        arguments: [~, App\Entity\UserLog, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: '来访记录' }
