#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: App\Controller\Admin\AdminController
    type: annotation
    prefix: "%admin_path%"