easy_admin:
    entities:
        Article:
            class: App\Entity\Article
            label: '文章信息'
            form:
                fields:
                    - {property: id, label: 'ID标识'}
                    - {property: title, label: '标题'}
                    - {property: keywords, label: '关键词'}
                    - {property: description, label: '描述'}
                    - {property: summary, label: '摘要'}
                    #- {property: titleImg, label: '标题图片'}
                    - { property: 'imageFile', type: 'vich_image', label: '标题图片' }
                    - {property: content, label: '内容'}
                    - {property: categories, label: '标签', type: 'App\Form\Type\TagsType'}
            list:
                fields:
                    - { property: 'titleImg', type: 'image', base_path: '%app.path.article_images%' }
                    - {property: title, label: '标题'}
                    - {property: keywords, label: '关键词'}
                    - {property: description, label: '描述'}
                    - {property: author, label: '作者'}
                    - {property: createdAt, label: '创建时间'}
                    - {property: updatedAt, label: '更新时间'}
            edit:
                fields:
                    - '-id'